/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevtestsViewerinputhookRouteImport } from './routes/devtests/viewerinputhook'
import { Route as DevtestsReferencestripRouteImport } from './routes/devtests/referencestrip'
import { Route as DevtestsMousetrackerRouteImport } from './routes/devtests/mousetracker'
import { Route as DevtestsCanvasdragendRouteImport } from './routes/devtests/canvasdragend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtestsViewerinputhookRoute = DevtestsViewerinputhookRouteImport.update({
  id: '/devtests/viewerinputhook',
  path: '/devtests/viewerinputhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtestsReferencestripRoute = DevtestsReferencestripRouteImport.update({
  id: '/devtests/referencestrip',
  path: '/devtests/referencestrip',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtestsMousetrackerRoute = DevtestsMousetrackerRouteImport.update({
  id: '/devtests/mousetracker',
  path: '/devtests/mousetracker',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtestsCanvasdragendRoute = DevtestsCanvasdragendRouteImport.update({
  id: '/devtests/canvasdragend',
  path: '/devtests/canvasdragend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devtests/canvasdragend': typeof DevtestsCanvasdragendRoute
  '/devtests/mousetracker': typeof DevtestsMousetrackerRoute
  '/devtests/referencestrip': typeof DevtestsReferencestripRoute
  '/devtests/viewerinputhook': typeof DevtestsViewerinputhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devtests/canvasdragend': typeof DevtestsCanvasdragendRoute
  '/devtests/mousetracker': typeof DevtestsMousetrackerRoute
  '/devtests/referencestrip': typeof DevtestsReferencestripRoute
  '/devtests/viewerinputhook': typeof DevtestsViewerinputhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devtests/canvasdragend': typeof DevtestsCanvasdragendRoute
  '/devtests/mousetracker': typeof DevtestsMousetrackerRoute
  '/devtests/referencestrip': typeof DevtestsReferencestripRoute
  '/devtests/viewerinputhook': typeof DevtestsViewerinputhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devtests/canvasdragend'
    | '/devtests/mousetracker'
    | '/devtests/referencestrip'
    | '/devtests/viewerinputhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devtests/canvasdragend'
    | '/devtests/mousetracker'
    | '/devtests/referencestrip'
    | '/devtests/viewerinputhook'
  id:
    | '__root__'
    | '/'
    | '/devtests/canvasdragend'
    | '/devtests/mousetracker'
    | '/devtests/referencestrip'
    | '/devtests/viewerinputhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevtestsCanvasdragendRoute: typeof DevtestsCanvasdragendRoute
  DevtestsMousetrackerRoute: typeof DevtestsMousetrackerRoute
  DevtestsReferencestripRoute: typeof DevtestsReferencestripRoute
  DevtestsViewerinputhookRoute: typeof DevtestsViewerinputhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtests/viewerinputhook': {
      id: '/devtests/viewerinputhook'
      path: '/devtests/viewerinputhook'
      fullPath: '/devtests/viewerinputhook'
      preLoaderRoute: typeof DevtestsViewerinputhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtests/referencestrip': {
      id: '/devtests/referencestrip'
      path: '/devtests/referencestrip'
      fullPath: '/devtests/referencestrip'
      preLoaderRoute: typeof DevtestsReferencestripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtests/mousetracker': {
      id: '/devtests/mousetracker'
      path: '/devtests/mousetracker'
      fullPath: '/devtests/mousetracker'
      preLoaderRoute: typeof DevtestsMousetrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtests/canvasdragend': {
      id: '/devtests/canvasdragend'
      path: '/devtests/canvasdragend'
      fullPath: '/devtests/canvasdragend'
      preLoaderRoute: typeof DevtestsCanvasdragendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevtestsCanvasdragendRoute: DevtestsCanvasdragendRoute,
  DevtestsMousetrackerRoute: DevtestsMousetrackerRoute,
  DevtestsReferencestripRoute: DevtestsReferencestripRoute,
  DevtestsViewerinputhookRoute: DevtestsViewerinputhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
